name: design_system
description: App resources.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.16
  cached_network_image: ^3.3.0
  responsive_framework: ^1.1.0
  rive: ^0.13.11

  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  global_lints:
    path: ../global_lints

