name: global_lints
description: Global lints for both apps and all local packages.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  lint: ^1.10.0
  flutter_lints: ^5.0.0
