name: ui_kit
description: App resources.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../design_system

  ui_kit_interface:
    path: ../ui_kit_interface

  dots_indicator: ^3.0.0
  flutter_animate: ^4.5.2
  top_snackbar_flutter: ^3.0.0+1
  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  global_lints:
    path: ../global_lints

flutter:

  fonts:
    - family: icons
      fonts:
        - asset: assets/icon_font/icons.ttf